//! URIs of the atom library.

pub const URI: &[u8] = b"http://lv2plug.in/ns/ext/atom\0";

pub const ATOM_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Atom\0";
pub const ATOM_PORT_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#AtomPort\0";
pub const BLANK_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Blank\0";
pub const BOOL_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Bool\0";
pub const CHUNK_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Chunk\0";
pub const DOUBLE_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Double\0";
pub const EVENT_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Event\0";
pub const FLOAT_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Float\0";
pub const INT_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Int\0";
pub const LITERAL_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Literal\0";
pub const LONG_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Long\0";
pub const NUMBER_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Number\0";
pub const OBJECT_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Object\0";
pub const PATH_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Path\0";
pub const PROPERTY_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Property\0";
pub const RESOURCE_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Resource\0";
pub const SEQUENCE_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Sequence\0";
pub const SOUND_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Sound\0";
pub const STRING_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#String\0";
pub const TUPLE_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Tuple\0";
pub const URI_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#URI\0";
pub const URID_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#URID\0";
pub const VECTOR_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#Vector\0";
pub const ATOM_TRANSFER_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#atomTransfer\0";
pub const BEAT_TIME_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#beatTime\0";
pub const BUFFER_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#bufferType\0";
pub const CHILD_TYPE_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#childType\0";
pub const EVENT_TRANSFER_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#eventTransfer\0";
pub const FRAME_TIME_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#frameTime\0";
pub const SUPPORTS_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#supports\0";
pub const TIME_UNIT_URI: &[u8] = b"http://lv2plug.in/ns/ext/atom#timeUnit\0";
